### PR TITLE
Add graphic interface and integration

### PR DESCRIPTION
**Pull request by CarMoreno**
Hi Yati, your genetic algorithm implementation in Python was helpful for a task in my University, I used your implementation and only added a tiny graphic interface with model-view-control architecture. I hope you like. :relieved:

### CODE REVIEW

**Comment by yati-sagade** [comment]
Hello Carlos, I'm glad that this was helpful to you. Thank you so much for the patch :) I'll review it as I get time.

It would be awesome if we could keep both interfaces to the program (your GUI interface and the console based interface for people who do not have Qt/PyQt), and this might require some refactoring here and there. Great job, thanks :)

**Comment by yati-sagade** [comment]
BTW: I also have a [Rust version of this](https://github.com/yati-sagade/exprolution), which is much faster :)

**Comment by CarMoreno** [comment]
Thanks to you and no problem Yati :), the next days I'm going to add console based interface.

**Comment by CarMoreno** [comment]
Hello again Yati, today I have refactored the code and I have integrated both, GUI interface and console based interface through a options menu. Now all user can choose how they want running application. I hope you like, below I added a image of main screen. Merry Christmas :)

image

**Comment by CarMoreno** [comment]
Hi Yati, so what happen? :)

**Comment by CarMoreno** [comment]
Hi Yati, so what happened? :) the pull request doesn't work?

**Pull request closed without merging**
